#!/usr/bin/env python3

import re
import sys

regex_list = []
with open(sys.argv[1], 'r') as inp:
    for line in inp:
        line = line.strip()
        if not line: continue
        regex_list.append(line)

with open(sys.argv[2], 'r') as inp, open(sys.argv[3], 'w') as out:
    for line in inp:
        line = line.strip()
        if not line: continue

        results = []
        for r in regex_list:
            try:
                results.append(len(re.findall(r, line)))
            except re.error:
                results.append(-1)
        out.write(" ".join(str(res) for res in results) + '\n')

